// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PMS.Api.Data;

#nullable disable

namespace PMS.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251211131022_pinformupdated")]
    partial class pinformupdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PMS.Api.Models.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Escalated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("PMS.Api.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DigitalSignatureStatus")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PMS.Api.Models.DrbDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidencePackageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecidedById");

                    b.HasIndex("ProjectId");

                    b.ToTable("DrbDecisions");
                });

            modelBuilder.Entity("PMS.Api.Models.OapForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("text");

                    b.Property<string>("AssuranceLevel")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DigitalSignatureStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstContactMeetingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("FormData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OpportunityCharacteristics")
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Roadmap")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("ProjectId");

                    b.ToTable("OapForms");
                });

            modelBuilder.Entity("PMS.Api.Models.PcapForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DigitalSignatureStatus")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("FormData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("GlobalDamControls")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedAssuranceProducts")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueImprovingPractices")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("ProjectId");

                    b.ToTable("PcapForms");
                });

            modelBuilder.Entity("PMS.Api.Models.PinForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessImpactAnalysis")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CurrentMitigations")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateRegistered")
                        .HasColumnType("date");

                    b.Property<string>("Dg1Comments")
                        .HasColumnType("text");

                    b.Property<string>("Dg1Decision")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Dg1DecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dg1DecisionById")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DrbApprovalDate")
                        .HasColumnType("date");

                    b.Property<string>("DrbMeetingRef")
                        .HasColumnType("text");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("text");

                    b.Property<string>("FactsAndAssumptions")
                        .HasColumnType("text");

                    b.Property<string>("FinancialBenefitsAnalysis")
                        .HasColumnType("text");

                    b.Property<string>("InterfaceDetails")
                        .HasColumnType("text");

                    b.Property<bool>("IsBreakIn")
                        .HasColumnType("boolean");

                    b.Property<string>("MtoNo")
                        .HasColumnType("text");

                    b.Property<string>("OpportunityCostNonImplementation")
                        .HasColumnType("text");

                    b.Property<string>("ProblemStatements")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectObjective")
                        .HasColumnType("text");

                    b.Property<string>("ProposalNo")
                        .HasColumnType("text");

                    b.Property<string>("ProposedProjectNo")
                        .HasColumnType("text");

                    b.Property<string>("ShutdownRemarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueAtRisk")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Dg1DecisionById");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("PinForms");
                });

            modelBuilder.Entity("PMS.Api.Models.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("PortfolioName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("PMS.Api.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovedCostUsd")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date");

                    b.Property<string>("ComplexityLevel")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LocationArea")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextDgDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OverallHealth")
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectLocationArea")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .HasColumnType("text");

                    b.Property<int>("Roadmap")
                        .HasColumnType("integer");

                    b.Property<string>("SapSyncStatus")
                        .HasColumnType("text");

                    b.Property<string>("SapWbsCode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TempProjectId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainUnitNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrentPhase");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("ProjectNumber")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DeliverableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsAttached")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBrownfieldHealthCheck")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PinId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PinId");

                    b.ToTable("ProjectPinAttachments");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinCo2Screening", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Co2AbatementCostUsdPerTonne")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("CteDate")
                        .HasColumnType("date");

                    b.Property<string>("CteName")
                        .HasColumnType("text");

                    b.Property<byte[]>("CteSignature")
                        .HasColumnType("bytea");

                    b.Property<decimal?>("ExpectedCo2ChangeTonnePerYear")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExpectedCostUsdPerYear")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PinId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("PsuDate")
                        .HasColumnType("date");

                    b.Property<string>("PsuName")
                        .HasColumnType("text");

                    b.Property<byte[]>("PsuSignature")
                        .HasColumnType("bytea");

                    b.Property<string>("ScenarioDescription")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PinId")
                        .IsUnique();

                    b.ToTable("ProjectPinCo2Screenings");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinInterfaceSignOff", b =>
                {
                    b.Property<Guid>("PinId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("TfiDate")
                        .HasColumnType("date");

                    b.Property<string>("TfiName")
                        .HasColumnType("text");

                    b.Property<string>("TfiRef")
                        .HasColumnType("text");

                    b.Property<byte[]>("TfiSignature")
                        .HasColumnType("bytea");

                    b.HasKey("PinId");

                    b.HasIndex("PinId")
                        .IsUnique();

                    b.ToTable("ProjectPinInterfaceSignOffs");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinMtoScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("AssessmentDate")
                        .HasColumnType("date");

                    b.Property<string>("AssessorName")
                        .HasColumnType("text");

                    b.Property<string>("AssessorRef")
                        .HasColumnType("text");

                    b.Property<byte[]>("AssessorSignature")
                        .HasColumnType("bytea");

                    b.Property<string>("MtoScore")
                        .HasColumnType("text");

                    b.Property<Guid>("PinId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PinId")
                        .IsUnique();

                    b.ToTable("ProjectPinMtoScores");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinRamAssessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("HeadSafetyDate")
                        .HasColumnType("date");

                    b.Property<string>("HeadSafetyName")
                        .HasColumnType("text");

                    b.Property<string>("HeadSafetyRef")
                        .HasColumnType("text");

                    b.Property<byte[]>("HeadSafetySignature")
                        .HasColumnType("bytea");

                    b.Property<string>("LikelihoodAsset")
                        .HasColumnType("text");

                    b.Property<string>("LikelihoodCommunity")
                        .HasColumnType("text");

                    b.Property<string>("LikelihoodEnvironment")
                        .HasColumnType("text");

                    b.Property<string>("LikelihoodPeople")
                        .HasColumnType("text");

                    b.Property<string>("LikelihoodReputation")
                        .HasColumnType("text");

                    b.Property<string>("LikelihoodSecurity")
                        .HasColumnType("text");

                    b.Property<string>("OverallRiskScore")
                        .HasColumnType("text");

                    b.Property<Guid>("PinId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScenarioDescription")
                        .HasColumnType("text");

                    b.Property<byte?>("SeverityAsset")
                        .HasColumnType("smallint");

                    b.Property<byte?>("SeverityCommunity")
                        .HasColumnType("smallint");

                    b.Property<byte?>("SeverityEnvironment")
                        .HasColumnType("smallint");

                    b.Property<byte?>("SeverityPeople")
                        .HasColumnType("smallint");

                    b.Property<byte?>("SeverityReputation")
                        .HasColumnType("smallint");

                    b.Property<byte?>("SeveritySecurity")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PinId")
                        .IsUnique();

                    b.ToTable("ProjectPinRamAssessments");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinStakeholder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("PinId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefInd")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Signature")
                        .HasColumnType("bytea");

                    b.Property<DateOnly?>("SignedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PinId");

                    b.ToTable("ProjectPinStakeholders");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinValueDriver", b =>
                {
                    b.Property<Guid>("PinId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueDriverCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ValueDriverName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PinId", "ValueDriverCode");

                    b.ToTable("ProjectPinValueDrivers");
                });

            modelBuilder.Entity("PMS.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PMS.Api.Models.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId1");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("PMS.Api.Models.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedRole")
                        .HasColumnType("text");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlaHours")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("PMS.Api.Models.ActionItem", b =>
                {
                    b.HasOne("PMS.Api.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("PMS.Api.Models.Project", "Project")
                        .WithMany("ActionItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.Api.Models.Document", b =>
                {
                    b.HasOne("PMS.Api.Models.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Api.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("PMS.Api.Models.DrbDecision", b =>
                {
                    b.HasOne("PMS.Api.Models.User", "DecidedBy")
                        .WithMany()
                        .HasForeignKey("DecidedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMS.Api.Models.Project", "Project")
                        .WithMany("DrbDecisions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.Api.Models.OapForm", b =>
                {
                    b.HasOne("PMS.Api.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("PMS.Api.Models.Project", "Project")
                        .WithMany("OapForms")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.Api.Models.PcapForm", b =>
                {
                    b.HasOne("PMS.Api.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("PMS.Api.Models.Project", "Project")
                        .WithMany("PcapForms")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.Api.Models.PinForm", b =>
                {
                    b.HasOne("PMS.Api.Models.User", "Dg1DecisionBy")
                        .WithMany()
                        .HasForeignKey("Dg1DecisionById");

                    b.HasOne("PMS.Api.Models.Project", "Project")
                        .WithOne("PinForm")
                        .HasForeignKey("PMS.Api.Models.PinForm", "ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Dg1DecisionBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.Api.Models.Project", b =>
                {
                    b.HasOne("PMS.Api.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMS.Api.Models.Portfolio", "Portfolio")
                        .WithMany("Projects")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinAttachment", b =>
                {
                    b.HasOne("PMS.Api.Models.PinForm", "Pin")
                        .WithMany("Attachments")
                        .HasForeignKey("PinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pin");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinCo2Screening", b =>
                {
                    b.HasOne("PMS.Api.Models.PinForm", "Pin")
                        .WithOne("Co2Screening")
                        .HasForeignKey("PMS.Api.Models.ProjectPinCo2Screening", "PinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pin");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinInterfaceSignOff", b =>
                {
                    b.HasOne("PMS.Api.Models.PinForm", "Pin")
                        .WithOne("InterfaceSignOff")
                        .HasForeignKey("PMS.Api.Models.ProjectPinInterfaceSignOff", "PinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pin");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinMtoScore", b =>
                {
                    b.HasOne("PMS.Api.Models.PinForm", "Pin")
                        .WithOne("MtoScore")
                        .HasForeignKey("PMS.Api.Models.ProjectPinMtoScore", "PinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pin");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinRamAssessment", b =>
                {
                    b.HasOne("PMS.Api.Models.PinForm", "Pin")
                        .WithOne("RamAssessment")
                        .HasForeignKey("PMS.Api.Models.ProjectPinRamAssessment", "PinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pin");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinStakeholder", b =>
                {
                    b.HasOne("PMS.Api.Models.PinForm", "Pin")
                        .WithMany("Stakeholders")
                        .HasForeignKey("PinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pin");
                });

            modelBuilder.Entity("PMS.Api.Models.ProjectPinValueDriver", b =>
                {
                    b.HasOne("PMS.Api.Models.PinForm", "Pin")
                        .WithMany("ValueDrivers")
                        .HasForeignKey("PinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pin");
                });

            modelBuilder.Entity("PMS.Api.Models.WorkflowInstance", b =>
                {
                    b.HasOne("PMS.Api.Models.Project", "Project")
                        .WithMany("Workflows")
                        .HasForeignKey("ProjectId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PMS.Api.Models.WorkflowStep", b =>
                {
                    b.HasOne("PMS.Api.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("PMS.Api.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("PMS.Api.Models.PinForm", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Co2Screening");

                    b.Navigation("InterfaceSignOff");

                    b.Navigation("MtoScore");

                    b.Navigation("RamAssessment");

                    b.Navigation("Stakeholders");

                    b.Navigation("ValueDrivers");
                });

            modelBuilder.Entity("PMS.Api.Models.Portfolio", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PMS.Api.Models.Project", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Documents");

                    b.Navigation("DrbDecisions");

                    b.Navigation("OapForms");

                    b.Navigation("PcapForms");

                    b.Navigation("PinForm");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("PMS.Api.Models.WorkflowInstance", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
